name: CI - SonarCloud Scan

on:
  push:
    branches:
      - "main"
      - "feature/*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: .github/workflows/reusable-java-build.yml
    with:
      maven-command: "mvn clean verify"
      artifact-path: "target"

  # Sonar Scan
  sonar-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download compiled artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: target

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-cache

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ vars.SONAR_ORG_KEY }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN